name: PUSH-CI

on:
  push:
    branches: [master, main]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: nacos-${{ github.ref }}

env:
  DOCKER_REPO: wuyfeedocker/nacos-ci

jobs:
  dist-tar:
    name: Deploy nacos-server
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        version: ["8", "9"]
        mode: ["cluster", "standlone"]
    steps:
      - name: run_number
        run: |
            number=$(expr ${{ github.run_number }} + 30000)
            echo ${{ matrix.version }} + ${number}
      - name: run_id
        run: |
            number=$(expr ${{ github.run_id }} + 30000)
            echo ${{ matrix.version }} + ${number}
      - name: job_id
        run: |
            number=$(expr ${{ strategy.job-index }} + 30000)
            echo ${{ matrix.version }} + ${number}
      - name: run_attempt
        run: |
            number=$(expr ${{ github.run_attempt }} + 30000)
            echo ${{ matrix.version }} + ${number}
      - name: getNum
        run: |
            number=$(expr $(expr 4*$(expr ${{ github.run_number }}-1)+${{ strategy.job-index }}))
      
