name: PUSH-CI

on:
  push:
    branches: [master, main]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: nacos-${{ github.ref }}

env:
  DOCKER_REPO: wuyfeedocker/nacos-ci

jobs:
  dist-tar:
    name: Deploy nacos-server
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        version: ["8", "9"]
        mode: ["cluster", "standlone"]
    steps:
      - name: Deploy nacos
        run: |
            number=${{ github.run_number }}+30000
            echo ${{ matrix.version }} + ${number}
